development:
  host: 127.0.0.1
  user: testing
  cert: private-cert

production:
  host: 127.0.0.1
  user: testing
  cert: private-cert

staging:
  host: 127.0.0.1
  user: testing
  cert: private-cert
